source "https://rubygems.org"

gem "rage-rb"

# Build JSON APIs with ease
# gem "alba"

# Get 50% to 150% boost when parsing JSON.
# Rage will automatically use FastJsonparser if it is available.
# gem "fast_jsonparser"
